name: Publish Python Package to PyPI

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: read

jobs:
  pypi-publish:
    name: Publish Python Package to PyPI
    runs-on: ubuntu-latest
    environment:
      name: testpypi # testpypi
      url: https://test.pypi.org/project/aprint # testpypi
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
    - name: Build package
      run: python -m build
    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with: # testpypi
        repository-url: https://test.pypi.org/legacy/ # testpypi normal commit
